# Site settings
title: Noob Academic
description: >
  Senza ingathi siyafunda. Ukuba nawe ufunda ukuba ngathi uyafunda,
  ufikile apho ubhalele khona.

author:
  fullname: Zola Mahlaza
  googleplus: https://www.google.com/+AdeebNqo
  github: AdeebNqo
  # disqus: your_disqus_username

 google_analytics: 'UA-66155430-4'

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
markdown: kramdown
