title:            Noob Academic
description:      Senza ingathi siyafunda. Ukuba nawe ufunda ukuba ngathi uyafunda,
  ufikile apho ubhalele khona.
url:              # Site url, without a slash at the end.
signoff:          Zola Mahlaza.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: "UA-66155430-4" # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Reads
    url:          /toread
  - name:         GitHub
    url:          http://github.com/adeebnqo
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
