title: Mahlaza on NLG
description: Writings from the guy reads random stuff

url: http://adeebnqo.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Reading
   url: /toread

social:
   github: adeebnqo
   twitter: nqongeveg
   email: adeebnqo@gmail.com

google_analytics: "UA-66155430-4"
